# Site Settings
title: Introduction to Digital Signal Processing
email: ald@iastate.edu
description: >
  EE 424 class web site.
baseurl: ""
url: "http://localhost:4000"
#twitter_username: taniarascia
#github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
