# Site Settings
title: Start Jekyll
email: taniarascia@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/ee424" # the subpath of your site, e.g. /blog
url: "htttp://isucsp.github.io/ee424" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: taniarascia
github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
