# Site Settings
title: Introduction to Digital Signal Processing
email: ald@iastate.edu
description: >
  EE 424 class web site.
baseurl: "/ee424" # the subpath of your site, e.g. /blog
url: "htttp://isucsp.github.io/ee424" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: taniarascia
#github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
